### ISSUE TITLE
Integration with `qibo`

### ISSUE THREAD

**Issue by renatomello** [qclib/qclib#180]
Would you guys be interested in a collaboration to integrate this library with the [`qibo` project](https://github.com/qiboteam/qibo)?

We are specially interested in integrating the linear-depth decomposition of multi-controlled $U(2)$ and $SU(2)$, since it is needed in some of our recent [work](https://arxiv.org/abs/2405.20408) as well as some of our work in progress (e.g. https://github.com/qiboteam/qibo/pull/1373).

We'd like to integrate the library to `qibo` but without creating `qiskit` dependencies.

**Comment by adjs** [comment]
Hi, @renatomello! Yes, we are interested in collaborating. I will contact you via email.
