### ISSUE TITLE
Join Qiskit Ecosystem

### ISSUE THREAD

**Issue by frankharkins** [qclib/qclib#184]
Thanks for maintaining this project! Would you be interested in submitting this project to the Qiskit ecosystem? It'd put qclib in front of more users and also puts the project on our radar so we know how Qiskit is being used.

Links:
* [Ecosystem web page](https://www.ibm.com/quantum/ecosystem)
* [Submission form](https://github.com/Qiskit/ecosystem/issues/new?template=submission.yml)

**Comment by adjs** [comment]
Hi, @frankharkins. Thank you for suggesting the submission of qclib to the qiskit ecosystem. @israelferrazaraujo, could you please fill out the submission form?

**Comment by israelferrazaraujo** [comment]
Hi @adjs, I will proceed with completing the submission form.

@frankharkins, thank you for your message and for considering the project for submission to the Qiskit ecosystem.

**Comment by israelferrazaraujo** [comment]
@adjs and @frankharkins,
Thanks for your support!
